baseURL = "http://docs.devritchiecli.io"
title = "Ritchie"
enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["ritchie"]

# Will give values to .Lastmod etc.
enableGitInfo = true

staticDir = ["static"]

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
angledQuotes = false
hrefTargetBlank = true
latexDashes = true
plainIDAnchors = true

# Image processing configuration.
[imaging]
anchor = "smart"
quality = 75
resampleFilter = "CatmullRom"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
contentDir = "content/en"
description = "A Docsy example site"
languageName = "English"
title = "Ritchie"
# Weight used for sorting.
version_menu = "Versions"
weight = 1

[[languages.en.menu.main]]
    name = "About"
    weight = 20
    url = "/reference/about-ritchie/"
[[languages.en.menu.main]]
    name = "FAQ"
    weight = 20
    url = "/reference/faq/"
[[languages.en.menu.main]]
    name = "Glossary"
    weight = 20
    url = "/reference/glossary/"

[languages.pt-br]
contentDir = "content/pt-br"
description = "Documentação Ritchie"
languageName = "Português"
title = "Ritchie"
version_menu = "Versões"

[[languages.pt-br.menu.main]]
    name = "Sobre"
    weight = 20
    url = "/pt-br/referência/sobre-ritchie"
[[languages.pt-br.menu.main]]
    name = "FAQ"
    weight = 20
    url = "/pt-br/referência/faq/"
[[languages.pt-br.menu.main]]
    name = "Glossário"
    weight = 20
    url = "/pt-br/referência/glossário"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "native"
# Uncomment if you want your chosen highlight style used for code blocks without a specified language
# guessSyntax = "true"

# Everything below this are Site Params

[params]
copyright = "Zup IT"
privacy_policy = "https://insights.zup.com.br/politica-privacidade"
version_path = ""
logoName = "icons/ritchie.svg"

isDocumentationDeprecated = false

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/ZupIT/ritchie-docs"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/ZupIT/ritchie-docs"

github_branch = "main"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = ""

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

[[params.versions]]

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.en]
version_menu = "Versions"

[params.pt-BR]
version_menu = "Versões"

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
desc = "Follow us on Instagram to get the latest news!"
icon = "fab fa-instagram"
name = "Instagram"
url = "https://www.instagram.com/zupinnovation"
[[params.links.user]]
desc = "Follow us on Linkedin to get the latest news!"
icon = "fab fa-linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/company/zup-it-solutions/"
[[params.links.user]]
desc = "Follow us on Youtube to get the latest news!"
icon = "fab fa-youtube"
name = "Youtube"
url = "https://www.youtube.com/channel/UCJWZyJ-36yNscqnnHiwjkhQ"
[[params.links.user]]
desc = "Follow us on Twitter to get the latest news!"
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/ZupInnovation"
[[params.links.user]]
desc = "Follow us on Medium to get the latest news!"
icon = "fab fa-medium"
name = "Medium"
url = "https://medium.com/zup-it"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
desc = "Development takes place here!"
icon = "fab fa-github"
name = "GitHub"
url = ""
[[params.links.developer]]
desc = "Chat with other project developers"
icon = "fab fa-slack"
name = "Slack"
url = ""
[[params.links.developer]]
desc = "Discuss development issues around the project"
icon = "fa fa-envelope"
name = "Developer mailing list"
url = ""
