name: Build production manually with version as input
on:
  workflow_dispatch:
    inputs:
        docs_version:
          description: 'Docs version (e.g.: v2.11, to be used in the URL & S3 bucket regardless of the branch name -- if not set, the semver segment from the branch name is used)'
          required: true
        checkout_ref:
          description: 'The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event. Otherwise, uses the default branch.'
          required: false

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PRD }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.inputs.checkout_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD }}
          aws-region: sa-east-1

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: S3 upload (images)
        run: aws s3 sync --follow-symlinks static/shared s3://$AWS_S3_BUCKET/shared/ --delete

      - name: Remove static images
        shell: bash
        working-directory: static
        run: rm -rf shared

      - name: Install dependencies
        run: yarn

      - name: Config proxy
        run: sed -i "s/\${latest_version}/${{ github.event.inputs.docs_version }}/" .github/workflows/proxy/index.html
        shell: bash

      - name: Config version path
        shell: bash
        run: sed -i -E "s/version_path = .*/version_path = \"\/${{ github.event.inputs.docs_version }}\"/g" config.toml

      - name: Build
        run: hugo -D --minify -b $BASE_URL/${{ github.event.inputs.docs_version }}
        env:
          BASE_URL: https://docs.ritchiecli.io

      - name: S3 upload to version subdir
        run: aws s3 sync --follow-symlinks public s3://$AWS_S3_BUCKET/${{ github.event.inputs.docs_version }}/ --delete

      - name: S3 upload (redirect to latest version)
        run: aws s3 sync --follow-symlinks .github/workflows/proxy s3://$AWS_S3_BUCKET




