name: Build staging (with the same steps from the build/workflow for PRD)

on:
  workflow_dispatch:
    inputs:
        docs_version:
          description: 'Docs version (e.g.: v2.11, to be used in the URL & S3 bucket regardless of the branch name -- if not set, the semver segment from the branch name is used)'
          required: false

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STG }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
          aws-region: sa-east-1

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: S3 upload (images)
        run: aws s3 sync --follow-symlinks static/shared s3://$AWS_S3_BUCKET/shared/ --delete

      - name: Remove static images
        shell: bash
        working-directory: static
        run: rm -rf shared

      - name: Install dependencies
        run: yarn

      - name: Get version from branch name if the docs_version var isn't present
        if: ${{ !github.event.inputs.docs_version }}
        id: version-if-no-docs_version
        run: echo "::set-output name=branch_version::$(echo $GITHUB_REF | sed 's/refs\/heads\/release-//g' )"
        shell: bash

      - name: Or else, get docs_version from workflow_dispatch
        if: ${{ github.event.inputs.docs_version }}
        id: version-if-docs_version
        run: echo "::set-output name=branch_version::${{ github.event.inputs.docs_version }}"
        shell: bash

      - name: Config version path
        shell: bash
        run: sed -i -E "s/version_path = .*/version_path = \"\/$VERSION\"/g" config.toml
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}

      - name: Build
        run: hugo -D --minify -b $BASE_URL
        env:
          BASE_URL: https://docs.stgritchiecli.io
          VERSION: ${{ steps.version.outputs.branch_version }}

      - name: S3 upload
        run: aws s3 sync --follow-symlinks public s3://$AWS_S3_BUCKET --delete
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}
