name: Build staging

on:
  push:
    branches:
    - main

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STG }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
          aws-region: sa-east-1

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: Install dependencies
        run: yarn

      - name: Build
        run: hugo -D --minify -b $BASE_URL
        env:
          BASE_URL: https://docs.stgritchiecli.io

      - name: S3 upload
        run: aws s3 sync --follow-symlinks public s3://$AWS_S3_BUCKET --delete
